services:
  db:
    image: postgres
    env_file: .env
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/role.sh:/docker-entrypoint-initdb.d/init-database.sh

volumes:
  pgdata: