services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
      POSTGRES_USER: chee
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chee -d example"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/role.sh:/docker-entrypoint-initdb.d/init-database.sh

volumes:
  pgdata: